spring:
  application:
    name: flyway
  datasource:
    url: jdbc:mysql://localhost:3306/flyway?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
server:
  port: 8083
